### PR TITLE
fix up gallery list that was staggered for some reason

### PR DESCRIPTION
**Pull request by joesaraceno**
for some reason the `<li>` items contained in here were not lined up correctly. Flex is an easy fix, and should only impact this content component in esdp's.

### CODE REVIEW

**Comment by marcuslyons** [comment]
@joesaraceno Flex is an easy fix, but will this cause incompatibility issues with patients? I'm not sure what our intended browser support is with esdp's.

**Comment by nathanlogan** [comment]
> @joesaraceno Flex is an easy fix, but will this cause incompatibility issues with patients? I'm not sure what our intended browser support is with esdp's.

I wondered the same.  Also, has a designer checked off on the margin/spacing change?

**Comment by marcuslyons** [comment]
After looking into more of the core components, it looks like we're using flex everywhere. So I think this isn't as big of a deal for this PR, but we need to figure that support out.

**Comment by joesaraceno** [comment]
After design inspection, I am off a few px. Tweaking those values now.
 
According to QA here, our esdp support matches "whatever microsoft supports", so I think we are good with using flex here.

**Pull request merged**
