### PR TITLE
:sparkles: refactor: replaced dependency on material-ui with semantic Dialog element

### PR DESCRIPTION
**Pull request by marcuslyons**
Removed the `material-ui Dialog` component and replaced it with an HTML Dialog.

Removed the dependency on the `material-ui DialogContent` component.

Removed the usage of `withStyles` from `material-ui`

### CODE REVIEW

**Review by nathanlogan — APPROVED** [review]
1. Is the idea here is to do the work, merge it to master, and wait until we have Material fully removed before we iterate the version and release it on npm?
2. Given that this is now an HTML dialog, do we need to remove some `propTypes`, and fix their logic throughout the component?

**Comment by nathanlogan** [comment]
One other question: we've been updating the CHANGELOG manually.  Is that something we want to do here, as well, or were you wanting to move away from that approach starting now?

**Comment by marcuslyons** [comment]
> 1. Is the idea here is to do the work, merge it to master, and wait until we have Material fully removed before we iterate the version and release it on npm?
> 2. Given that this is now an HTML dialog, do we need to remove some `propTypes`, and fix their logic throughout the component?

1. That's what I was thinking. Merge this one in and not bump the version or release, wait for the full v3 release for that.
2. Good call, I should probably remove those propTypes, but leaving them in isn't a big deal either. The component works as-is without making any changes to the Storybook demos, which means any application using the Modal won't have to make any changes to continue using it.

**Comment by marcuslyons** [comment]
> One other question: we've been updating the CHANGELOG manually. Is that something we want to do here, as well, or were you wanting to move away from that approach starting now?

I can update it if we want to, or we can wait for the v3 release. I'm good either way.

**Pull request merged**
